### ISSUE TITLE
Keyboard restyling

### ISSUE THREAD

**Issue by Rinnegatamante** [Rinnegatamante/easyrpg-player-3ds#15]
The currently used keyboard is just a really fast-made ones with Paint. A better-looking ones could be very nice <.< . Layout should match the current one if possible.

Current keyboard can be found here (flip it vertically to have the original image): https://raw.githubusercontent.com/Rinnegatamante/easyrpg-player-3ds/master/data/keyboard.bmp

**Comment by gnmmarechal** [comment]
I've sent you one via Rinnegatamante forums

**Comment by masterfeizz** [comment]
I did a little mockup, but since I'm not a huge fan of giant buttons I made it into a square grid. Threw in some colors trying to give it some life. If you like it I can finish it and tweak the code also to make it work with this layout.
![Imgur](http://i.imgur.com/vhk2p2M.png)
Or I can also make a full keyboard, I don't know if its necessary since I'm not too familiar with rpg maker

**Comment by Ghabry** [comment]
Imo the keyboard should have a dark color (almost black) with a not too bright outline and with not too bright (light grey) text because the bright color is annoying for the eyes when you play in the dark ;)

I like the squared layout @masterfeizz suggested because it looks like a normal keypad... We only need the following (based on the numpad of my Android calc app):

```
7 | 8 | 9 | /
4 | 5 | 6 | *
1 | 2 | 3 | -
. | 0 | ? | +
```

The ? is really just placeholder. Because we don't need further keys... So maybe stretch the 0 a bit like on PC keypads:

```
7 | 8 | 9 | /
4 | 5 | 6 | *
1 | 2 | 3 | -
  0   | . | +
```

**Comment by gnmmarechal** [comment]
![keyb_dark](https://cloud.githubusercontent.com/assets/11259227/14320221/362d5af2-fc0c-11e5-802f-f14b44138a91.png)
BMP: https://mega.nz/#!mIYWQSpD!HRtQJTneOC6MEA9H_JvLyw5RX7-vC8TTDuJNdTyksR0
PDN: https://mega.nz/#!WYoRUIJb!7g1qtNAambO_c66AFbFh-fudlwnpVGkZ_CS__bb1zOA
Flipped BMP: https://mega.nz/#!fBYDiA7A!midUPKVRrt5IZI6ADaEVZ0KSr-63STL91kiv_-qFI9U

I actually like the original layout, which is why I've kept it.

**Comment by ItsSchoko** [comment]
Hey guys.

I agree on @Ghabry's suggestion making the keypad like one that we all know from our smartphone/tablet, for better usability.

So, I threw you something together:

3D_ish:
![easyrpg_3ds_keypad](https://cloud.githubusercontent.com/assets/17786862/14331111/1ed8401e-fc44-11e5-96ee-fd1bf135aa33.png)

flat:
![easyrpg_3ds_keypad_flat](https://cloud.githubusercontent.com/assets/17786862/14331121/2522ec26-fc44-11e5-9b2b-bc92a87c4cd9.png)

PNG/BMP also on Dropbox:
https://www.dropbox.com/sh/0zqznc8x7v7sar5/AAA3wRGJsiHA-Itbbn7rNzQia/Nintendo_3ds

I'm already thinking about creating pixelated characters, so every part is exactly on the (pixel)grid and the characters won't look washed out.

EDIT:

clean background for games that don't need a keypad:
![easyrpg_3ds_keypad_background](https://cloud.githubusercontent.com/assets/17786862/14351565/4f8ef608-fcd0-11e5-92bf-dfe5b3337a82.png)

**Comment by Rinnegatamante** [comment]
@ItsSchoko , i like the first one, going to implement it right now, thanks for your help!

**Comment by Rinnegatamante** [comment]
Implemented with https://github.com/Rinnegatamante/easyrpg-player-3ds/commit/0495145f1bc9f49668b41298a4936fad3b9ce4c0

**Comment by gnmmarechal** [comment]
nice, looks awesome

**Comment by carstene1ns** [comment]
One thing i thought of just now is the possibility to map additional Player functionality to virtual buttons on the second screen.
For example there could be a screenshot button or a FPS toggle button which indicates the current state. Thinking this further, also an Options button (for the to be implemented option scene, used to toggle music/change volume, etc.) would be possible.

Maybe add them separated by some visual border as a top row or on the right/left.
This is, however, just a suggestion. No idea if these are actually wanted by the users.

**Comment by Rinnegatamante** [comment]
@carstene1ns Could be done but it needs a major rewrite since, as of now, on bottom screen there is only a single image blended once before player starts to not cause framedrops by updating bottom screen too at every frame.

**Comment by ItsSchoko** [comment]
@carstene1ns Good point, I also thought about such features.

How about a keypad with hamburger menu, which could then toggle between screens?
![easyrpg_3ds_keypad_menu](https://cloud.githubusercontent.com/assets/17786862/14431543/6521b814-0006-11e6-9b79-e9c0018fc61c.png)

BGM/Effects toggles could be useful, I'm not sure about sliders if there's hardware volume control.
